version: '3'

networks:
  laravel:

volumes:
  db-volume:
  redis-volume:

services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx
    depends_on:
      - php
      - mysql
    environment:
      - TZ=Asia/Tokyo
    networks:
      - laravel
  
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_NAME: mysql
      TZ: Asia/Tokyo
    networks:
      - laravel
    volumes:
      - db-volume:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./logs:/var/log/mysql
      
  php:
    build:
      context: ./docker/php
    container_name: php
    volumes:
      - ./src:/var/www/html
      - ./docker/php/php.laravel.ini:/usr/local/etc/php/conf.d/lwaravel.php.ini
      - ./logs:/var/log/php
    ports:
      - 9000:9000
    networks:
      - laravel
  
  node:
    image: node:13
    container_name: node
    tty: true
    volumes:
      - ./src:/work
    working_dir: /work
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=homestead
      - PMA_PASSWORD=secret
    links:
      - mysql
    ports:
      - 8081:80
    networks:
      - laravel
      
  redis:
    image: redis:alpine
    container_name: redis
    ports: 
      - 6379:6379
    volumes:
      - redis-volume:/data
    networks:
      - laravel
  
  mail:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - 8025:8025
    networks:
      - laravel