version: '3'

networks:
  laravel:

volumes:
  db-volume:

services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel
  
  mysql:
    image: mysql:5.7.29
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_NAME: mysql
    networks:
      - laravel
    volumes:
      - db-volume:/var/lib/mysql
      
  php:
    build:
      context: ./docker/php
    container_name: php
    volumes:
      - ./src:/var/www/html
      - ./docker/php/php.laravel.ini:/usr/local/etc/php/conf.d/lwaravel.php.ini
      - ./logs:/var/log/php
    ports:
      - "9000:9000"
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=homestead
      - PMA_PASSWORD=secret
    links:
      - mysql
    ports:
      - 8081:80
    networks:
      - laravel
      
  redis:
    image: redis:alpine
    container_name: redis
    ports: 
      - 6379:6379
    networks:
      - laravel